version: "3.8"

services:
  web:
    build: .
    command: ./start-dev.sh
    ports:
      - "8000:8000"
    environment:
      - DEBUG=true
      - DB_ENGINE=sqlite
      - DB_NAME=db.sqlite3
      - VERSION=${VERSION:-1.0.0-dev}
    volumes:
      - .:/app
