version: "3.8"

services:
  web:
    build: .
    command: ./start-dev.sh
    ports:
      - "8000:8000"
    environment:
      - DEBUG=false
      - DATABASE_URL=sqlite:////app/db.sqlite3
    volumes:
      - .:/app
    depends_on: []

  db:
    image: postgres:15-alpine
    profiles: [ "donotrun" ]
